// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu247sTM_H7t2LSKdERvdD4yujuE8MfIs',
    appId: '1:759229690424:web:6b2ad1d76cdede4e27accd',
    messagingSenderId: '759229690424',
    projectId: 'petrolpump-fc3d2',
    authDomain: 'petrolpump-fc3d2.firebaseapp.com',
    storageBucket: 'petrolpump-fc3d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrzcMMF5-VuIegF3aVXbuiLxgGsuNYTcE',
    appId: '1:759229690424:android:845ead8a364504ae27accd',
    messagingSenderId: '759229690424',
    projectId: 'petrolpump-fc3d2',
    storageBucket: 'petrolpump-fc3d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6wLl322MfCDAueF1t2jlS2FrWK8V2JKg',
    appId: '1:759229690424:ios:04feed6030b782ee27accd',
    messagingSenderId: '759229690424',
    projectId: 'petrolpump-fc3d2',
    storageBucket: 'petrolpump-fc3d2.appspot.com',
    iosBundleId: 'com.example.petrolpumdealerchayan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6wLl322MfCDAueF1t2jlS2FrWK8V2JKg',
    appId: '1:759229690424:ios:3785f94ef858ba7e27accd',
    messagingSenderId: '759229690424',
    projectId: 'petrolpump-fc3d2',
    storageBucket: 'petrolpump-fc3d2.appspot.com',
    iosBundleId: 'com.example.petrolpumdealerchayan.RunnerTests',
  );
}
